### ISSUE TITLE
tag feature to create a downloadable copy of a specific release?

### ISSUE THREAD

**Issue by hwpplayer1** [kpu/intgemm#108]
Thank you for creating intgemm and releasing it as free software. Because it is free software, I would like to add intgemm to the Free Software Foundation's Free Software Directory (FSD). What is preventing me from doing so is the FSD's requirement to review a specific version of a given project. The best way for us to review a specific version is if a project uses the tag feature of github. Would you be willing to use the tag feature to create a downloadable copy of a specific release?

[0]: https://directory.fsf.org/

Thank you for your consideration.

**Comment by kpu** [comment]
Ok, https://github.com/kpu/intgemm/releases/tag/v1.0
