### ISSUE TITLE
Keep multiplication pure

### ISSUE THREAD

**Issue by kpu** [kpu/intgemm#23]
The multiply code should take a template argument for what it does with C.  If there's a postprocess pipeline implemented using that template argument, fine.  But the multiplier (i.e. multiply.h) should not impose that on users.

**Comment by mateuszchudyk** [comment]
wip branch: https://github.com/kpu/intgemm/tree/callbacks-and-kernels

**Comment by kpu** [comment]
Cool.  I think `dvector_t` is overkill.  We could just have multiply call the callback twice.  Or use std::pair.

**Comment by mateuszchudyk** [comment]
Callbacks and kernels has been merged.

**Comment by mateuszchudyk** [comment]
Do we want to do something more in this issue or we can close it?
