### ISSUE TITLE
Documentation for postprocessing

### ISSUE THREAD

**Issue by kpu** [kpu/intgemm#41]
@XapaJIaMnu says "Also, adding a new postprocessing function is no longer very obvious, we should have a description for that."

**Comment by kpu** [comment]
This looks bad:
https://github.com/kpu/intgemm/blame/master/README.md#L45

**Comment by mateuszchudyk** [comment]
Is it enough?
https://github.com/kpu/intgemm/commit/b79de3e879ce2fa50078778a203e1d17f9c89c33
