### ISSUE TITLE
Is the ChooseCPU function fast enough?

### ISSUE THREAD

**Issue by kpu** [kpu/intgemm#5]
Did we just decide that ChooseCPU should run every call?

**Comment by XapaJIaMnu** [comment]
We didn't, I did.... I suppose you want the fn ptr stored separately in another class and having a function that just calls it... Will do it tonight

**Comment by XapaJIaMnu** [comment]
Is b99ac68c71ab1c6117e585815986d4e5ad167ce9 what you are looking for?

**Comment by kpu** [comment]
Yes, let's merge it.
