### ISSUE TITLE
Allow CPUID downgrade via environment variable

### ISSUE THREAD

**Issue by kpu** [kpu/intgemm#84]
Would be useful for regression testing to get exact outputs rather than CPU dependence.

**Comment by jerinphilip** [comment]
cmdline option along with environment variable, please? Would make a few bash scripts cleaner. Linking https://github.com/browsermt/marian-dev/issues/17 to enable notifications.

**Comment by kpu** [comment]
If you want a command line, Marian would need to be refactored to directly call the intgemm arch variant classes (already exposed by intgemm) instead of the CPU dispatch.

**Comment by kpu** [comment]
b578ae4521229c53ba0512be3d562b0afbd68fd4
