### ISSUE TITLE
Support "-fno-exceptions" flag

### ISSUE THREAD

**Issue by yurydelendik** [kpu/intgemm#91]
Is it possible to add "-fno-exceptions" support? Just providing alternative to throw codepath with `#ifdef __EXCEPTIONS` (e.g. `std::abort()`) shall fix the issue

Currently, when I include intgemm source as part of Firefox build, I'm getting "STL code can only be used with -fno-exceptions" error.

**Comment by kpu** [comment]
Yes

**Comment by kpu** [comment]
Is the a MSVC equivalent for `__EXCEPTIONS`?

**Comment by yurydelendik** [comment]
> Is there a MSVC equivalent for `__EXCEPTIONS`?

I see `_HAS_EXCEPTIONS` in some sources
